const gameTitle=document.querySelector("#level-title")
// const green=document.querySelector('#green')
// const red=document.querySelector('#red')
// const blue=document.querySelector('#blue')
// const yellow=document.querySelector('#yellow')